name: execute

on:
  workflow_dispatch:

jobs:
  access-alpacadevv:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.15.0'

    - name: Install dependencies
      run: yarn install --immutable --immutable-cache

    - name: Access alpacadevv
      run: |
        yarn execute
        echo what? ${{ secrets.TEST_ENV }} | sed 's/ ./& /g'
      env:
        TEST_ENV: ${{ secrets.TEST_ENV }}
